version: "3.1"

services:
  sci:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fnirs-apps/sci
    volumes:
      - /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data/:/bids_dataset
    command: ["--task_label", "tapping", "--threshold", "0.6"]
