version: "3.1"

services:
  sci:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fnirs-apps/sci
    volumes:
      - /Volumes/MassStorage2TB/rluke/Repositories/BIDS-NIRS-Tapping/:/data
    command: ["0.6"]
